services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres_db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-locations_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      TZ: Europe/Moscow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: nizhny_maps
    ports:
      - "8501:8501"
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-locations_db}
      - YANDEXGPT_API_KEY=${YANDEXGPT_API_KEY}
      - YANDEXGPT_FOLDER_ID=${YANDEXGPT_FOLDER_ID}
    volumes:
      - ./data_:/app/data_

  caddy:
    image: caddy:2
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - app

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
