[project]
name = "nizniy-maps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "geoalchemy2>=0.18.0",
    "geopy>=2.4.1",
    "openpyxl>=3.1.5",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.44",
    "streamlit>=1.51.0",
    "streamlit-folium>=0.25.3",
    "streamlit-js-eval>=0.1.7",
]
